In [1]:
import tensorflow as tf

In [32]:
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Conv2DTranspose(
    1,
    (3, 3),
    strides=(2, 2),
    output_padding=(1, 1),
    input_shape=(2, 2, 1)
))
model.summary()

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_transpose_11 (Conv2D  (None, 6, 6, 1)          10        
 Transpose)                                                      
                                                                 
Total params: 10
Trainable params: 10
Non-trainable params: 0
_________________________________________________________________


In [33]:
layer = model.layers[0]
current_w, current_bias = layer.get_weights()  # see the current weights
current_w.shape

(3, 3, 1, 1)

In [34]:
new_w = tf.constant([[1, 0, 1],
                     [0, 0, 0],
                     [1, 0, 1]])
new_w = tf.reshape(new_w, current_w.shape)  # fix the shape

In [43]:
new_bias = tf.constant([0])
layer.set_weights([new_w, new_bias])

In [44]:
model.summary()
tf.print(model.layers[0].get_weights())

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_transpose_11 (Conv2D  (None, 6, 6, 1)          10        
 Transpose)                                                      
                                                                 
Total params: 10
Trainable params: 10
Non-trainable params: 0
_________________________________________________________________
[array([[[[1.]],

        [[0.]],

        [[1.]]],


       [[[0.]],

        [[0.]],

        [[0.]]],


       [[[1.]],

        [[0.]],

        [[1.]]]], dtype=float32),
 array([0.], dtype=float32)]


In [45]:
import numpy as np
X = np.asarray([[1, 3],
                [2, 4]])
# show input data for context
print(X)
# reshape input data into one sample a sample with a channel
X = X.reshape((1, 2, 2, 1))
model.predict(X)

[[1 3]
 [2 4]]


array([[[[ 1.],
         [ 0.],
         [ 4.],
         [ 0.],
         [ 3.],
         [ 0.]],

        [[ 0.],
         [ 0.],
         [ 0.],
         [ 0.],
         [ 0.],
         [ 0.]],

        [[ 3.],
         [ 0.],
         [10.],
         [ 0.],
         [ 7.],
         [ 0.]],

        [[ 0.],
         [ 0.],
         [ 0.],
         [ 0.],
         [ 0.],
         [ 0.]],

        [[ 2.],
         [ 0.],
         [ 6.],
         [ 0.],
         [ 4.],
         [ 0.]],

        [[ 0.],
         [ 0.],
         [ 0.],
         [ 0.],
         [ 0.],
         [ 0.]]]], dtype=float32)